/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CPythonAdapter */

#ifndef _Included_CPythonAdapter
#define _Included_CPythonAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CPythonAdapter
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;[LSymbol;)V
 */
JNIEXPORT void JNICALL Java_CPythonAdapter_run
  (JNIEnv *, jobject, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
